name: CI/CD Pipeline

# Trigger the pipeline on push and pull_request events for the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job for the testing and building process
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run tests using unittest
    - name: Run tests (unittest)
      run: |
        echo "Running unit tests..."
        python -m unittest discover -s tests -p "*.py"  # Assuming your test files are in a folder named "tests"

    # Step 5: Build Docker image (if you're using Docker)
    - name: Build Docker image (if you're using Docker)
      run: |
        docker build -t retail-data-pipeline-image .

  # Job for deploying to Google Cloud (assuming you're using GCP)
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Google Cloud authentication
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    # Step 3: Deploy to Google Cloud
    - name: Deploy to Google Cloud
      run: |
        gcloud config set project retail-data-pipeline
        gcloud app deploy --quiet
